# rule 3
# select the direct information and 
# the information about those objects having an anonymous node (1 level deep) and
# selected information about those objects that are SKOS:Concepts 
#


construct {
	<SUBJECT> ?p ?o.
        ?o ?op ?oo.
        ?o skos:prefLabel ?label.
} 
where {

	<SUBJECT> ?p ?o.
        OPTIONAL {
         filter (anon(?o)).
         ?o ?op ?oo.
        }
        OPTIONAL {
          ?o a skos:Concept.
          ?o skos:prefLabel ?label.
       }
}

